### ISSUE TITLE
Not working with CB 2.0.7

### ISSUE THREAD

**Issue by ghost** [pgasiorowski/plg_emailactivation#1]
Hey,

I'm trying to use this plugin with Joomla 3.4.0 and CB 2.0.7. On the frontend (the user-part) it seems to work as described. On the backend the new address is not recognized. The mail that the user gets to re-activate the account is not working because the account is still blocked after clicking the link inside the mail.

Also deactivating the "block user"- and "auto logoff"-setting doesn't help. There is the information on the frontend that a mail has been sent and again, after clicking the new re-activation link, nothing happens. The address inside the user-list is still the old one.

I have to disable the whole plugin. After that it is possible for the user to change the address, but without the re-activation I'd like to have.

Would be happy to get an updated and working version. :-)

Thanks in advance.

**Comment by pgasiorowski** [comment]
Hi @paraflyer,
Thanks for reporting,
I'll take a look in the next few days. Haven't tested it yet with either J3.4 or CB2.x
