### ISSUE TITLE
Send copy email to admin

### ISSUE THREAD

**Issue by sshcli** [pgasiorowski/plg_emailactivation#3]
Add the option to send a copy of the email to the administrator.
So the admin can be notified every time a user changes his/her email.

**Comment by pgasiorowski** [comment]
It should be possible to use `Execute on successful activation` plugin parameter to do that.

```php
$mailer = JFactory::getMailer();
$mailer->setSender(['from@example.com', 'Admin']);
$mailer->addRecipient('sendto@email.com');
$mailer->setSubject('Your subject string');
$mailer->setBody("Old: $oldEmail new: $email");
$mailer->Send();
```

More details at https://docs.joomla.org/Sending_email_from_extensions

**Comment by sshcli** [comment]
Ok, 
Thanks

**Comment by pgasiorowski** [comment]
I'm going to close this but feel free to send a pull request
